[audio]
device = "default"
sample_rate = 16000
channels = 1

[whisper]
model = "whisper-large-v3-turbo"  # Groq API model (also supports whisper-large-v3)
language = "en"
use_api = true
api_provider = "groq"  # Options: "groq" (default, faster & cheaper) or "openai"
api_endpoint = "https://api.groq.com/openai/v1/audio/transcriptions"
# Set GROQ_API_KEY environment variable for Groq
# For OpenAI: set api_provider = "openai" and OPENAI_API_KEY environment variable

[ui]
indicator_position = "top-right"
indicator_size = 20
show_notifications = true
layer_shell_anchor = "top | right"
layer_shell_margin = 10

[wayland]
input_method = "wtype"
use_hyprland_ipc = true

[behavior]
auto_paste = true
preserve_clipboard = false
delete_audio_files = true
audio_feedback = true  # Play sounds for recording start/stop
