[audio]
device = "default"
sample_rate = 16000
channels = 1

[whisper]
model = "base"
language = "en"

[ui]
indicator_position = "top-right"
indicator_size = 20
show_notifications = true
layer_shell_anchor = "top | right"
layer_shell_margin = 10

[wayland]
input_method = "wtype"
use_hyprland_ipc = true

[behavior]
auto_paste = true
preserve_clipboard = false
delete_audio_files = true
audio_feedback = true  # Play distinctive beep tones for start/stop/complete